# Generated by Django 5.1.6 on 2025-02-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('MongoDB', 'MongoDB'), ('React js', 'Reactjs'), ('ExpressJs', 'ExpressJs'), ('Nodejs', 'Nodejs'), ('SQL', 'SQL'), ('WEB_TECH', 'WEB_TECH'), ('DJango', 'Django'), ('Spring', 'Spring'), ('HyberNet', 'HyberNet'), ('SpringBoot', 'SpringBoot')], max_length=100)),
                ('Technical', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=200)),
                ('Communication', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=100)),
                ('Programming', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('conducted_on', models.DateField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
