# Generated by Django 5.1.6 on 2025-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='Communication',
            field=models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='Programming',
            field=models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='Technical',
            field=models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('MongoDB', 'MongoDB'), ('React js', 'Reactjs'), ('ExpressJs', 'ExpressJs'), ('Nodejs', 'Nodejs'), ('SQL', 'SQL'), ('WEB_TECH', 'WEB_TECH'), ('DJango', 'Django'), ('Spring', 'Spring'), ('HyberNet', 'HyberNet'), ('SpringBoot', 'SpringBoot')], default='Python', max_length=100),
        ),
    ]
