# Generated by Django 5.1.6 on 2025-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='add',
            field=models.CharField(max_length=50),
        ),
    ]
